### ISSUE TITLE
Return icon images on search responses

### ISSUE THREAD

**Issue by michogar** [geomatico/tmb.js#17]
Library needs manage statics files like images, icons... These files will be in a shared static folder but we don't know yet the exact location, library must have this option configurable, maybe setting the URL of the static folder location.

**Comment by oscarfonts** [comment]
We don't have a complete algorithm, so let's return _something_ (could be a placeholder), then refine.

**Comment by michogar** [comment]
There is a [comment](https://trello.com/c/LocENJnW/107-componente-busqueda) on Trello Card about this issue.
