### ISSUE TITLE
Simplify search interface

### ISSUE THREAD

**Issue by oscarfonts** [geomatico/tmb.js#18]
1. To avoid redundancies, `api.search.search(query)` will be `api.search.query(text, options)`. Options could be, for instance, a `resultsPerPage` valid only for this specific query.
2. Default paramete values will be exposed in an `api.search.config` configuration object. The first property to be implemented is `resultsPerPage`. Changing its value will affect any subsequent queries.

**Comment by michogar** [comment]
:+1: to set parameters at query time, but maybe it is interesting allow set some parameters at instantiation time too.
