### ISSUE TITLE
Replace api.search call with a mock

### ISSUE THREAD

**Issue by michogar** [geomatico/tmb.js#6]
Search test not works in travis

**Comment by oscarfonts** [comment]
- Would like to avoid exposing internal http object just for testing.
- Would be better to inject an axios instance with underlying http calls actually mocked ("adapter" config property does that).
- Test equals actual code...

**Comment by oscarfonts** [comment]
This seems te way to go:
https://github.com/jhnns/rewire
https://github.com/jhnns/rewire-webpack

How about browsers? Test in feature branch.
